name : My Test

on : 
  push :
    branches :
     - main

jobs :
  First_trial_test :
    runs-on : ubuntu-latest
    steps :
      - name : my_job_id
        run : | 
          echo "I made it"
  Print_date :
    runs-on : ubuntu-latest
    steps :
      - name : date_printer
        run : | 
          date
  display_list :
    runs-on : ubuntu-latest
    steps :
      - name : display_list_lenght
        run : |
          ls -l

      