name : Deployment pipeline

on :
  push :
    branches :
      - main

jobs :
  setup_env : 
    runs-on : ubuntu-latest
    defaults:
      run:
        shell: bash
    steps :
      - uses : actions/checkout@v6
      - uses : actions/setup-node@v6
        with : 
          node-version : '24'
      - name : install dependencies
        run : npm install
      - name : eslinting
        run : npm run eslint
      - name : building steps
        run : npm run build
      - name : testing stage
        run : npm run test
    